### ISSUE TITLE
ServiceBusQueue Health Check is sending the scheduled test message to the queue

### ISSUE THREAD

**Issue by itcotta** [Xabaril/AspNetCore.Diagnostics.HealthChecks#500] opened 2020-04-24 12:55 UTC
When the health check for ServiceBusQueue is executed sometimes (very rarely, something like a few times a month) a message with the Message Text: "HealthCheckTest" will actually end up in the service bus queue.

By having a quick look at the implementation here https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.AzureServiceBus/AzureServiceBusQueueHealthCheck.cs I can see that this is the message that actually ends up in the service bus queue comes from here. `private const string TEST_MESSAGE = "HealthCheckTest";` From what I can see, the way the health on the service bus queue is checked is by creating a scheduled message and cancelling before it is actually sent to the queue.

By looking at the current implementation I would expect the scheduled test message to never be actually sent to the queue. However this doesn't seem to always be the case. It seems like the scheduled message cancellation is not actually working sometimes.

Looking in the logs I can see that in `Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService` this message gets sent
`Health check "Queue" completed after 88.2696ms with status Unhealthy and 'null'`
and then two hours after the scheduled test message ends up in our service bus queue.

I'm unsure on how to reproduce the issue since it only occurs rarely and not very often.

- .NET Core version : .Net Core 3.1
- Healthchecks version: 3.0.0

**Comment by OlegTontici** [comment] 2020-05-15 08:02
I'm here to confirm the problem described.

Indeed, from time to time it happens that this message reaches the actual queue listener which in my case cause an exception because the message is not json formatted so it can not be properly deserialized without an intervention into the process.

- .NET Core version : .Net Core 2.2
- Healthchecks version: 2.2.4

**Comment by unaizorrilla** [comment] 2020-05-15 08:12
Hi @itcotta 

Thanks a lot for summit the issue, I try to take a look a soon as posible!

**Comment by itcotta** [comment] 2020-05-15 08:19
I can also confirm that this issue is present after updating to Healthchecks version: 3.1.1.

**Comment by unaizorrilla** [comment] 2020-05-15 08:24
Thanks I'm working on it now, let me some time to debug and trying to fix the issue!

**Comment by unaizorrilla** [comment] 2020-05-15 09:03
Hi @itcotta 

I'm finished how perform the health check and I removing subscription messages, In order to use ManagementClient instead of topic/queue client.

The problem is that is a breaking change because the information about requireSession / configuring message is not necesary right now!

**Comment by unaizorrilla** [comment] 2020-05-15 09:06
> 
> 
> I'm here to confirm the problem described.
> 
> Indeed, from time to time it happens that this message reaches the actual queue listener which in my case cause an exception because the message is not json formatted so it can not be properly deserialized without an intervention into the process.
> 
>     * .NET Core version : .Net Core 2.2
> 
>     * Healthchecks version: 2.2.4

Hi @OlegTontici 

Are you using ASP.NET Core 2.2 ? This is not supported right now, are you planning to update to 3.1?

**Comment by itcotta** [comment] 2020-05-15 09:18
> Hi @itcotta
> 
> I'm finished how perform the health check and I removing subscription messages, In order to use ManagementClient instead of topic/queue client.
> 
> The problem is that is a breaking change because the information about requireSession / configuring message is not necesary right now!
> 
> Are you using this parameters when register the healthcheck?

I'm registering it like this:

`              .AddHealthChecks()
                .AddAzureServiceBusQueue(
                    serviceBusSettings.ConnectionString,
                    serviceBusSettings.QueueSettings.QueueName,
                    serviceBusSettings.QueueName)
                .AddAzureServiceBusTopic(
                    serviceBusSettings.ConnectionString,
                    serviceBusSettings.TopicOrderStatusSettings.TopicPath,
                    serviceBusSettings.TopicName)`

**Comment by unaizorrilla** [comment] 2020-05-15 09:42
Hi @itcotta ,  @OlegTontici

The package 3.2.1 is published on NuGet. Can you test it and close the issue if this package solve the problems?

**Comment by OlegTontici** [comment] 2020-05-15 10:00
> Hi @OlegTontici
> 
> Are you using ASP.NET Core 2.2 ? This is not supported right now, are you planning to update to 3.1?

Yeah, we're using asp .net core 2.2, and indeed, soon we'll migrate to 3.1.

Going to test it, although it may take some time since it didn't happens on regular basis.
Will get back with my results.

Thanks.

**Comment by unaizorrilla** [comment] 2020-05-15 10:06
Ok @OlegTontici !! We remove the subscription/cancellation, It shouldn't happen again :-)

**Comment by itcotta** [comment] 2020-05-27 09:01
Closed it, seems to be fixed now :)

**Closed** 2020-05-27 09:01 UTC
Labels: bug, investigation
