### ISSUE TITLE
After release update from  6.0.4 to 6.1.0. , health check for Azure Service Bus Queue is broken. Throws Unauthorized access error.

### ISSUE THREAD

**Issue by bhavsarravi** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1724] opened 2023-03-03 12:07 UTC
What happened: After release update from  6.0.4 to 6.1.0. , health check for Azure Service Bus Queue is broken. Throws Unauthorized access error. 

What you expected to happen: We expect the same as how the AzureServiceBusQueue health check  was working with least privilege Service Bus Sender Role as in 6.0.4 version.

How to reproduce it (as minimally and precisely as possible): Just provide with least privilege Service Bus Sender Role.
I attempted to implement a health check for a queue using an identity assigned the "Azure Service Bus Data Sender" role.

Source code sample: 
![image](https://user-images.githubusercontent.com/16952430/222715218-232b6bd9-6df9-4c94-8212-7d02c5dca64f.png)

**Anything else we need to know?**:

Exact Error Received:
[Error] [] Health check "catalog-servicebus-check" with status Unhealthy completed after 12744.2465ms with message 'null'System.UnauthorizedAccessException: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://eus2-pind-sremark-atest.servicebus.windows.net/rdi-reportdata/$management'. TrackingId:11111111-2222-3333-4444-555555555555_G3, SystemTracker:NoSystemTracker, Timestamp:2023-03-02T02:47:07For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.

- .NET Core version 6.0
- Healthchecks version 6.1.0
- Operative system: Win
- Others:

**Comment by sungam3r** [comment] 2023-03-03 16:21
See #1565 . Did you try the latest preview packages?

**Comment by bhavsarravi** [comment] 2023-03-07 06:47
Hi @sungam3r, I tried with new Pre release package 7.0.0-rc2.4, and it doesn't work. I get some weird error and it breaks the existing code. 
However 6.0.4 version works perfectly fine with only "Azure Service Bus Data Sender" role and in 6.1.0 version due to this library change we need to provide additional role assignment of "Azure Service Bus Data Receiver".

**Comment by sungam3r** [comment] 2023-03-07 18:06
Would you like to post PR fixing it?

**Comment by marioleed** [comment] 2023-03-10 23:50
@sungam3r Latest prerelease package 7.0.0-rc2.4 doesn't seem to contain #1565.

@bhavsarravi When #1565 is released you should be able to use the new options parameter and set `.UsePeekMode = false;` and it should work as in 6.0.4.

```csharp
services.AddHealthChecks()
    .AddAzureServiceBusQueue("example.servicebus.windows.net", "queueName", options => 
    {
        options.UsePeekMode = false;
    });
```

**Comment by sungam3r** [comment] 2023-03-13 19:20
https://www.nuget.org/packages/AspNetCore.HealthChecks.AzureServiceBus/7.0.0-rc2.5

**Comment by marioleed** [comment] 2023-03-14 08:41
I have tested 7.0.0-rc5 and it seems to work as intended (with `UsePeekMode = false`) 👍🏻

**Comment by bhavsarravi** [comment] 2023-03-15 08:43
**I did tested version 7.0.0-rc2.5 using  (with UsePeekMode = false) configurations and its working now.**
Thank you so much for fixing it. Will we waiting to use it once released!

**Note:**
However it is observed that with this version there is a dependency require of library 'Microsoft.Bcl.AsyncInterfaces', which doesn't get added while installing this AspNetCore.HealthChecks.AzureServiceBus Nuget Package.
 
_Error : "FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)"_

This can be closed now!

**Comment by sungam3r** [comment] 2023-03-16 07:49
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1692#issuecomment-1441406963

**Comment by sungam3r** [comment] 2023-03-16 07:52
@bhavsarravi What is your TFM?

**Comment by marioleed** [comment] 2023-03-16 08:31
I actually get the same error in .NET 7 for `.AddAzureEventHub()`:

> Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

But not for `.AddAzureServiceBus()` 🤔

**Comment by sungam3r** [comment] 2023-03-16 08:50
I have a feeling this dependency problem should be fixed by MS but in real world we can end up with spreading #1720 fix across all packages.

**Comment by sungam3r** [comment] 2023-03-16 08:52
`AzureEventHubHealthCheck` calls `ClientCache.GetOrAddAsyncDisposableAsync` which explicitly uses `IAsyncDisposable`.

**Comment by sungam3r** [comment] 2023-07-05 23:05
Closing as fixed.

**Closed by sungam3r** 2023-07-05 23:05 UTC
Labels: needs confirmation
