### ISSUE TITLE
Problem with Health Check UI in .Net 6

### ISSUE THREAD

**Issue by mehdihadeli** [Xabaril/AspNetCore.Diagnostics.HealthChecks#890] opened 2021-12-31 17:53 UTC
Hi,
I upgrade my application to .net 6 after upgrade, health UI doesn't work. I got below exception:

``` bash
[21:22:25 INF] Initializing UI Database
[21:22:26 FTL] Host terminated unexpectedly
System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.MutablePropertyExtensions.SetValueComparer(Microsoft.EntityFrameworkCore.Metadata.IMutableProperty, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer)'.
   at HealthChecks.UI.Core.Data.Configuration.HealthCheckExecutionEntryMap.Configure(EntityTypeBuilder`1 builder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration`1 configuration)
   at HealthChecks.UI.Core.Data.HealthChecksDb.OnModelCreating(ModelBuilder modelBuilder)
```

``` csharp
public static IApplicationBuilder UseCustomHealthCheck(this IApplicationBuilder app)
{
    app.UseHealthChecks("/healthz", new HealthCheckOptions
    {
        Predicate = _ => true,
        ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse,
        ResultStatusCodes =
        {
            [HealthStatus.Healthy] = StatusCodes.Status200OK,
            [HealthStatus.Degraded] = StatusCodes.Status500InternalServerError,
            [HealthStatus.Unhealthy] = StatusCodes.Status503ServiceUnavailable,
        },
    }).UseHealthChecksUI(setup =>
    {
        setup.ApiPath = "/healthcheck";
        setup.UIPath = "/healthcheck-ui";
    });

    return app;
}
```

``` csharp
public static IServiceCollection AddCustomHealthCheck(this IServiceCollection services,
        Action<IHealthChecksBuilder> configurator = null)
    {
        var healCheckBuilder = services.AddHealthChecks();
        configurator?.Invoke(healCheckBuilder);

        //// health check ui has problem with .net 6
        // services.AddHealthChecksUI(setup =>
        // {
        //     setup.SetEvaluationTimeInSeconds(60); //time in seconds between check
        //     setup.AddHealthCheckEndpoint("Basic Health Check", "/healthz");
        // }).AddInMemoryStorage();

        return services;
    }
```

**Comment by carlosrecuero** [comment] 2022-01-03 15:47
Hi @mehdihadeli , I couldn't reproduce it. 
Could you please check the sample on the repo: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/master/samples/HealthChecks.UI.Sample with the following packages (the latest), and verify if it also works for you?:

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="6.0.2" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="6.0.2" />
  </ItemGroup>

**Comment by mehdihadeli** [comment] 2022-01-03 18:37
Hi @carlosrecuero,
Yes, I will check it.
Also this is the source of my sample project and my startup.
[https://github.com/mehdihadeli/partners-management](https://github.com/mehdihadeli/partners-management/blob/main/src/PartnersManagement.Api/Startup.cs)

**Comment by carlosrecuero** [comment] 2022-02-04 15:03
Hi @mehdihadeli , could you check it?

**Comment by mehdihadeli** [comment] 2022-02-04 18:22
@carlosrecuero  With the new version of your library, it works. 
Thanks

**Comment by carlosrecuero** [comment] 2022-02-04 18:55
Thank you for your answer @mehdihadeli . I close the issue.

**Closed by carlosrecuero** 2022-02-04 18:55 UTC

**Comment by mehdihadeli** [comment] 2022-02-04 21:17
> Thank you for your answer @mehdihadeli . I close the issue.

Thanks
