### ISSUE TITLE
SignalR healthcheck issue

### ISSUE THREAD

**Issue by ChrisProlls** [Xabaril/AspNetCore.Diagnostics.HealthChecks#524] opened 2020-05-12 18:45 UTC
Please, fill the following sections to help us fix the issue

**What happened**: I tried to use the SignalR healthcheck but I faced with a **Object reference not set to an instance of an object.** into the health check portal.
![image](https://user-images.githubusercontent.com/1511666/81731744-afddbc00-948f-11ea-9e28-318134c444f3.png)

**What you expected to happen**: I expect the health check to work properly

**Source code sample**: I used this code :
````csharp
services.AddHealthChecks()
                .AddSignalRHub("/Hub", name: "signalr hub")
                .AddSignalRHub("/UploaderHub", name: "signalr uploader")
                .AddHealthChecksUI(setup =>
                {
                    setup.AddHealthCheckEndpoint("HealthCheck", "/healthz");
                    setup.SetEvaluationTimeInSeconds(60);
                })
                .AddInMemoryStorage();
````

and for my route configuration

````csharp
app
                .UseHealthChecks("/healthz", new HealthCheckOptions
                {
                    Predicate = _ => true,
                    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
                })
                .UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHub<UploaderHub>("/UploaderHub");
                endpoints.MapHub<ClientHub>("/Hub");
                endpoints.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapRazorPages();
                endpoints.MapHealthChecksUI(options => options.UIPath = "/health-ui");
            });
````

Into the health check, I assume that this line returns null, but can't figure out why:
````csharp
new HubConnectionBuilder()
                    .WithUrl(url)
                    .Build();
````

**Anything else we need to know?**:
Ths UI portal is showing correctly, others health check (sql, redis) are working properly.

**Environment**:

- .NET Core version : 3.1.100
- Healthchecks version : 3.1.1
- Operative system: Windows

**Comment by unaizorrilla** [comment] 2020-05-15 07:59
Hi @ChrisProlls 

Thanks for submitting the issue! 

Well, the issue is related with your Uri configuration for the SignalR hubs. AddSignalRHub need the hub uri, not the path string, ie /hub.

When the healthcheck perform the iteration, the HubConnectionBuilder throw because this uri is not valid.

Can you set the valid Uri for the Hub and test if this works well?

Please, close the issue if this solve the problem!

**Comment by ChrisProlls** [comment] 2020-06-02 07:31
So, if I understand correctly, I need the full SignalR hub URL into my Startup ?
For example : `https://mydomain.com/hub` ?

Into the startup it's not possible to retrive the domain name, so I would have to store it into the configuration files.

**Comment by atwoodr** [comment] 2020-06-18 19:49
Hi @unaizorrilla, I'm essentially in the same exact situation as @ChrisProlls with the same lib versions, etc.  When I try my equivalent of `https://mydomain.com/hub`, I no longer get the "Object reference not set to an instance of an object" issue, but it still reports that the endpoint is unhealthy. 
 I double-checked that our signalR is working just fine in our app.  

I tried all these combinations and they all produced the same result (i.e. no error, but still unhealthy):
- `https://mydomain.com/`
- `https://mydomain.com/hub`
- `https://mydomain.com/Hub`

@ChrisProlls, were you able to see your endpoint as healthy with providing the full url in the way you mentioned above?

**Comment by unaizorrilla** [comment] 2020-06-23 10:37
@ChrisProlls 

Yeap, you need to set the uri in configuration vars! Is not easy to get the domain name at startup time

**Closed by unaizorrilla** 2020-06-23 10:37 UTC
Labels: investigation
