### ISSUE TITLE
SQL Healthchecks fail with Microsoft.Data.SqlClient.SqlAuthenticationProviderManager threw an exception

### ISSUE THREAD

**Issue by PeterStaev** [Xabaril/AspNetCore.Diagnostics.HealthChecks#522] opened 2020-05-05 15:02 UTC
Please, fill the following sections to help us fix the issue

**What happened**:
After update to the latest version of Healthchecks SQL Server checks started failing with the following error:
```
The type initializer for \u0027Microsoft.Data.SqlClient.SqlAuthenticationProviderManager\u0027 threw an exception.
```

**What you expected to happen**:
SQL Server Helathchecks to continue to work as normal. 

**How to reproduce it (as minimally and precisely as possible)**:
I'm using the following connection string:
```
Server=MyServer;Database=MyDb;Integrated Security=true;MultipleActiveResultSets=true
```
**Source code sample**:

**Anything else we need to know?**:
Version 3.0.0 of the SQL Server healthchecks were working fine, but anything after that it fails with the above error. Probably related to the change to use `Microsoft.Data.SqlClient`. 

**Environment**:

- .NET Core version: 3.1.2
- Healthchecks version: 3.1.1
- Operative system: Windows 10 Pro  Domain joined computer
- Others:

**Comment by unaizorrilla** [comment] 2020-05-15 08:09
Hi @PeterStaev 

I tested the package and it's works! Can you use our sample HealthCheck.Sample, and remove comments for 

` //.AddSqlServer(connectionString: Configuration["Data:ConnectionStrings:Sample"])`

on startup and tests your sql modifiying the connection string on 

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/46d5cc08866d00402c6c4952fbb92f7501492f27/samples/HealthChecks.Sample/appsettings.json#L13


On 3.0.0 we use Microsoft.Data.SqlClient because it's support more features that System.Data.SqlClient!

**Comment by PeterStaev** [comment] 2020-05-15 09:11
Hey @unaizorrilla , 

It is really strange. I have 3 projects that use the check all with the same connectionString. It works on 2, but fails on one with the above mentioned error... I will try to trace the problem and will let you know. If you have any idea what could be causing this error would appreciate it.

**Comment by unaizorrilla** [comment] 2020-05-15 09:23
Hi @PeterStaev 

waiting for more info.

Check if you have also referenced System.Data.SqlClient !!!

**Comment by PeterStaev** [comment] 2020-05-15 09:37
Yes, all my projects have reference to `System.Data.SqlClient`

**Comment by unaizorrilla** [comment] 2020-05-15 09:40
Can you remove this reference?  in theory Microsoft.Data.SqlClient have the same API surface! and more features..

**Comment by PeterStaev** [comment] 2020-05-15 09:42
No, as it is coming as a dependency from other nuget packages

**Comment by unaizorrilla** [comment] 2020-05-15 09:47
:-( , well on dotnet core Microsoft.Data.SqlClient is the recommended package!

Try to debug your project and if get more info, p**lease let me know!** I close the issue, but feel free to re open if your consider the issue is related!

**Closed by unaizorrilla** 2020-05-15 09:47 UTC
Labels: investigation
