### ISSUE TITLE
System.InvalidOperationException in Microsoft.Data.Sqlite.dll

### ISSUE THREAD

**Issue by AndreaLando** [Xabaril/AspNetCore.Diagnostics.HealthChecks#417] opened 2020-02-12 17:47 UTC
Hi, I am developing an UI health check web browser but when poll the sample endpoint http://localhost:8005/hc a have an exception and the /hc-ui remains blank.

System.Net.Http.HttpClient.health-checks.LogicalHandler: Information: Start processing HTTP request GET http://localhost:8005/hc
System.Net.Http.HttpClient.health-checks.ClientHandler: Information: Sending HTTP request GET http://localhost:8005/hc
System.Net.Http.HttpClient.health-checks.ClientHandler: Information: Received HTTP response after 23.1724ms - OK
System.Net.Http.HttpClient.health-checks.LogicalHandler: Information: End processing HTTP request after 28.363ms - OK
Eccezione generata: 'System.InvalidOperationException' in Microsoft.Data.Sqlite.dll

Attached here's my project.
[Manager2.zip](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/files/4193939/Manager2.zip)

**Comment by unaizorrilla** [comment] 2020-02-12 17:54
Let me some time to review the sample. Are you check our sample UiAndApi?

**Comment by AndreaLando** [comment] 2020-02-13 00:14
Yes i do.... Thanks for your interest.
--
Inviato da Libero Mail per Android mercoledì, 12 febbraio 2020, 06:54PM +01:00 da Unai Zorrilla  notifications@github.com :

**Comment by unaizorrilla** [comment] 2020-02-25 20:34
Hi @AndreaLando 

I check your sample and works fine for me (the endpoint you configure is not on my machine)

![imagen](https://user-images.githubusercontent.com/1630008/75285180-709bb980-5816-11ea-9482-4a0ec4ca7647.png)


I close the issue because I can't reproduce your problem. Please re-open if you have more info!

**Closed by unaizorrilla** 2020-02-25 20:34 UTC
Labels: bug
