### ISSUE TITLE
material.css has invalid woff2 file

### ISSUE THREAD

**Issue by JimPShaw** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2219] opened 2024-05-27 19:00 UTC
.Net core 8, chrome browser.

The material icons do not display properly (not loaded properly) due to an error in browser decoding the woff2 file for the material icons.

**Comment by dtwilliams10** [comment] 2024-05-27 23:04
Pretty sure this is a duplicate of #2130

**Comment by JimPShaw** [comment] 2024-05-28 13:34
Thanks, workaround is good.

**Comment by camiteca** [comment] 2024-06-12 15:57
The problem with the workaround is that it's only useful if you can reach the internet on your host.

**Comment by Jamie-Clayton** [comment] 2024-06-20 23:43
Fixed in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2217

**Comment by Alirexaa** [comment] 2024-07-26 17:21
close this as completed via #2217

**Closed by Alirexaa** 2024-07-26 17:21 UTC
