### ISSUE TITLE
How to use the K8S operator together with agic?

### ISSUE THREAD

**Issue by brechtvhb** [Xabaril/AspNetCore.Diagnostics.HealthChecks#633] opened 2020-09-16 10:49 UTC
Is it possible to use the K8S operator together with agic?

In my other apps I have an ingress.yml which lets the application gateway know how to reach the app

example:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coolservice-api-ingress
  namespace: global
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/request-timeout: "60"    
		
spec:
  rules:
  - http:
      paths:
      - path: /api/coolservice/*
        backend:
          serviceName: coolservice-api-service
          servicePort: 80
```

It is not entirely clear how I have to do this together with the operator which somehow already has options about what the UI path should be. Operators are a new concept for me.
Can anyone point me in the right direction?

**Comment by CarlosLanderas** [comment] 2020-09-16 11:07
@brechtvhb let me try to reproduce this scenario and add it to the docs, I think it could help many people with that have this same doubts.

**Comment by brechtvhb** [comment] 2020-09-16 18:36
I found a way to make it work with agic:

Heres the config of my healthchecks ui:

```
apiVersion: "aspnetcore.ui/v1"
kind: HealthCheck
metadata:
  name: healthchecks-ui
  namespace: healthchecks
spec:
  name: healthchecks-ui
  scope: Cluster
  servicesLabel: HealthChecks
  serviceType: ClusterIP
  uiPath: /health
  uiApiPath: /health/api
  uiResourcesPath: /health/static
  uiWebhooksPath: /health/webhooks
```

Here's my ingress YAML

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: healthchecks-ui-ingress
  namespace: healthchecks
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/request-timeout: "60"    
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "40"

spec:
  rules:
  - http:
      paths:
      - path: /health/*
        backend:
          serviceName: healthchecks-ui-svc
          servicePort: 80
      - path: /health
        backend:
          serviceName: healthchecks-ui-svc
          servicePort: 80         
```

**Comment by CarlosLanderas** [comment] 2020-09-16 18:50
Hello! Your config looks exactly like the one I was going to try. 

I have no issue with the operator even when I update services after several hours running. The default label is HealthChecks and not healthchecks. Could that be the problem?

It would be very useful to inspect the logs to see the operations the operator is carrying out 

Thanks!

**Comment by brechtvhb** [comment] 2020-09-16 19:22
I am using this as label

```
  labels:
    HealthChecks: enabled  
```

What logs should I examine?
When I check them the logs of the operator say nothing, when a service got added after several hours. Could the issue be that the service was already existing without HealthChecks label. The HealthChecks label was added in an update to my service and that change did not seem to get picked up by the operator.

**Comment by CarlosLanderas** [comment] 2020-09-16 19:41
No, that should be fine. I use to label/unlabel existing services all the time without issue. Tell me if you can see any aborted connection message in your logs that might indicate that the streaming connection against the cluster was closed.

**Comment by CarlosLanderas** [comment] 2020-09-16 20:03
@brechtvhb, are you labeling pods or services?

**Comment by brechtvhb** [comment] 2020-09-17 07:02
I am labeling services. Which one is the preferred way?

**Comment by CarlosLanderas** [comment] 2020-09-17 07:04
Good. Only services are watched inside the operator 👍. Closing this issue. Open a new one if you find problems with the operator again. I've been testing and can't reproduce it

**Closed by CarlosLanderas** 2020-09-17 07:04 UTC
