### ISSUE TITLE
UIResponseWriter.WriteHealthCheckUIResponse and the UI

### ISSUE THREAD

**Issue by espenrl** [Xabaril/AspNetCore.Diagnostics.HealthChecks#18] opened 2018-12-06 11:55 UTC
The output formatter returned by `UIResponseWriter.WriteHealthCheckUIResponse` seems to format the json document in a way the UI does not understand. I have followed the documentation and I can't get the UI up running.

**Comment by unaizorrilla** [comment] 2018-12-06 12:07
Are you check the samples? UI is working well, we have a issue with exception serialization, and working on it!

**Comment by CarlosLanderas** [comment] 2018-12-06 12:13
#16

**Comment by unaizorrilla** [comment] 2018-12-06 14:44
Hi @espenrl 

Can you try 2.2.2 version of the UI.Client and UI and check if the issue is solved?

**Comment by espenrl** [comment] 2018-12-06 17:56
v2.2.2 / latest version of Chrome

![image](https://user-images.githubusercontent.com/4621581/49602292-66c73580-f988-11e8-9e89-6b90a2a52328.png)

![image](https://user-images.githubusercontent.com/4621581/49602310-747cbb00-f988-11e8-91a6-034ef58130e0.png)

### variable A
![image](https://user-images.githubusercontent.com/4621581/49602335-7e062300-f988-11e8-802a-928f826a5643.png)

### A.filter
![image](https://user-images.githubusercontent.com/4621581/49602354-88c0b800-f988-11e8-802d-aec21b0840d2.png)

**Comment by espenrl** [comment] 2018-12-06 18:01
The same happens in latest version of Edge.

**Comment by unaizorrilla** [comment] 2018-12-06 18:15
The sample project for UI works for you? Can you create a repro?

Other guys are using the UI without issues

**Comment by espenrl** [comment] 2018-12-06 18:48
My bad. I had this setting pointing directly at the health endpoint. The confusing part was that it almost worked and I thought it was a polyfill issue (the json for the UI api endpoint and the health endpoint are almost the same). Thanks for the help!

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/70cff8d40451cd1057bab6c5512b4b7243f6a7df/src/HealthChecks.UI/Configuration/Options.cs#L7

**Comment by CarlosLanderas** [comment] 2018-12-06 18:59
@espenrl thank you  for the explanation. Exactly, the error .Filter of undefined is because the answer from the UI middleware returns a list and if you call directly to the health endpoint is an object. The UI should always call to the UI endpoint in order to work properly.

Thanks for the explanation. I Close the issue :)

**Closed** 2018-12-06 18:59 UTC

**Comment by panna-ahmed** [comment] 2019-08-09 20:39
@CarlosLanderas I have everything right but still getting this TypeError: A.filter is not a function error. 
Here are  my config:

app.UseHealthChecks("/health", new HealthCheckOptions()
            {
                Predicate = _ => true,
                ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
            })
            .UseHealthChecksUI(setup =>
            {
                setup.ApiPath = "/health";
                setup.UIPath = "/health-ui";

                //setup.UseRelativeApiPath = false;
                //setup.UseRelativeResourcesPath = false;
                //setup.UseRelativeWebhookPath = false;
            });

"HealthChecksUI": {
    "HealthChecks": [
      {
        "Name": "HTTP Basic",
        "Uri": "http://localhost:5000/health"
      }
    ],
    "Webhooks": [],
    "EvaluationTimeOnSeconds": 10,
    "MinimumSecondsBetweenFailureNotifications": 60
  }

and the response coming from server is:
{"status":"Healthy","totalDuration":"00:00:00.0005566","entries":{"posDatabase":{"data":{},"duration":"00:00:00.0005068","status":"Healthy"}}}

**Comment by kafeltz** [comment] 2019-08-22 14:57
@panna-ahmed same here... the server is returning a json the UI don't understand.

And taking a look at the source code `AspNetCore.Diagnostics.HealthChecks\src\HealthChecks.UI\client\components\LivenessPage.tsx` the input is really wrong. The `ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse` is not sending the correct json to the UI.

**Comment by CarlosLanderas** [comment] 2019-08-22 17:19
@panna-ahmed please check the documentation, you are setting the UI API to the same path of the healthchecks endpoint. That's why the UI is not retrieving the correct data.
