### ISSUE TITLE
MongoDb: support `3.x.x` driver

### ISSUE THREAD

**Issue by enricobenedos** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2339] opened 2024-12-06 10:23 UTC
**What would you like to be added**:
As per title, add support to Mongo driver V3.

**Why is this needed**:
To avoid runtime exceptions like:
```
File name: 'MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321'
   at HealthChecks.MongoDb.MongoDbHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.RunCheckAsync(HealthCheckRegistration registration, CancellationToken cancellationToken)
[10:16:56 ERR] Health check mongodb threw an unhandled exception after 0.7158ms
System.IO.FileNotFoundException: Could not load file or assembly 'MongoDB.Driver.Core, Version=2.28.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321'. The system cannot find the file specified.
```

**Comment by eerhardt** [comment] 2024-12-10 19:02
This was done in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2324. We are preparing a v9 release of HealthChecks that will include this support.

This is a duplicate of #2322.

**Closed by eerhardt** 2024-12-10 19:02 UTC
