### ISSUE TITLE
Version 8.0 - UI Resources

### ISSUE THREAD

**Issue by garild** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2146] opened 2024-01-19 09:00 UTC
Hi, 
Today after update the nugget version from 7.x.x to 8.0.0 we face with some UI issues, in this case I think we is missing some Font 

- HealthChecks.UI ="7.0.2" -> 8.0.0
- HealthChecks.UI.Client = "7.1.0" -> 8.0.0

![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/12533435/18c41dc6-f291-4954-bb64-2ffa4b2e3c1b)

- .NET Core version - 8
- Healthchecks version - 8.0.0
- Operative system: Windows/Linux
- Others:

**Comment by rob-baldwin** [comment] 2024-01-19 11:32
Duplicate of https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2130

**Comment by Jamie-Clayton** [comment] 2024-06-21 22:29
Resolved in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2217

**Closed** 2024-08-29 21:46 UTC
