### ISSUE TITLE
Healthchecks-api is getting slow after a while

### ISSUE THREAD

**Issue by Snoopysgit** [Xabaril/AspNetCore.Diagnostics.HealthChecks#97] opened 2019-02-15 11:03 UTC
We've configured healthchekcs-ui to check 25 healthchecks from our different apis.
The healthckeck is configured to perform a check every 10s.
After the first deployment everything worked fine and we got responses fast (around 200-400ms for a call to healthchecks-api).
After around 1 day of gathering, the UI starts to get very slow. It seems like the healthchekcs-api endpoint is performing slower ans slower, the more result is stored in the database. A call to healthchecks-api takes now around 2min...

**Comment by unaizorrilla** [comment] 2019-02-15 11:22
I try to verify asap, i think Database only mantain latest results but probably we have a problem here.

**Comment by unaizorrilla** [comment] 2019-02-16 22:59
Hi @Snoopysgit 

After review the code, I discover a bug saving entries on each execution. This populate entries table with a lot of information and after some time the system getting slow.

I fix the issue on 2.2.14, at this moment the build is on appveyor, when finish a new package will be on NuGet.org.

Thanks for fill this, if new version solve your problem please, close this!

**Comment by unaizorrilla** [comment] 2019-02-16 23:15
Version 2.2.14 is on NuGet -> https://www.nuget.org/packages/AspNetCore.HealthChecks.UI/

**Comment by Snoopysgit** [comment] 2019-02-18 11:22
Thanks for your fast feedback, very nice. We'll try out the new version asap and give feedback.

**Comment by ussamoo** [comment] 2019-02-20 09:43
First Thank you for the great job!

We have the same issue, but also we end up with a huge CPU usage that increase over time after the first deployment...

**Comment by unaizorrilla** [comment] 2019-02-21 09:42
Are you use the latest version?

**Comment by ussamoo** [comment] 2019-02-21 10:17
Unfortunately still the same issue with the version 2.2.16 !

![image](https://user-images.githubusercontent.com/8547025/53161395-39267b80-35ca-11e9-817a-c28caaa56695.png)

**Comment by unaizorrilla** [comment] 2019-02-21 10:20
Can you sendme a copy of healthchecks.db in order to check the number of items inside? This can help me a lot

**Comment by Snoopysgit** [comment] 2019-02-21 10:21
@unaizorrilla yes, we finally updated the package and deployed everything. Your fix solved the performance issue.
We have seen drastic reduction in CPU usage since our update on tuesday:
![image](https://user-images.githubusercontent.com/4614552/53161596-94586e00-35ca-11e9-9172-66709e1c53a5.png)

So for me the issue is fixed

**Comment by unaizorrilla** [comment] 2019-02-21 10:21
Ohh ok

> 
> 
> @unaizorrilla yes, we finally updated the package and deployed everything. Your fix solved the performance issue.
> We have seen drastic reduction in CPU usage since our update on tuesday:
> ![image](https://user-images.githubusercontent.com/4614552/53161596-94586e00-35ca-11e9-9172-66709e1c53a5.png)
> 
> So for me the issue is fixed

thanks a lot

**Closed** 2019-02-21 10:25 UTC
Labels: bug

**Comment by ussamoo** [comment] 2019-02-21 11:12
After double check i confirm that the issue is resolved! the graph was from the wrong server! sorry

**Comment by unaizorrilla** [comment] 2019-02-21 11:25
Not worries! Happy of os solved!

**Comment by tellybrown** [comment] 2019-03-04 22:17
I would think not having a using statement around the HttpClient would cause an issue.  I know there was a blog post around not doing this for .net framework but I don't believe that core behaves the same way.

```
        protected internal virtual Task<HttpResponseMessage> PerformRequest(string uri)
        {
            return new HttpClient().GetAsync(uri);
        }
        private async Task<UIHealthReport> GetHealthReport(HealthCheckConfiguration configuration)
        {
            var (uri, name) = configuration;
            try
            {
                var response = await PerformRequest(uri);

                return await response.As<UIHealthReport>();
            }
            catch (Exception exception)
            {
                _logger.LogError(exception, "GetHealthReport throw the exception.");

                return new UIHealthReport(
                    entries: new Dictionary<string, UIHealthReportEntry>(),
                    totalDuration: TimeSpan.FromSeconds(0));
            }
        }
```

**Comment by unaizorrilla** [comment] 2019-03-04 23:15
I think Ihttpclientfactory can be the best idea to use here! Let me some days to check this
