### ISSUE TITLE
SendGrid Health Check  Method not found Exception

### ISSUE THREAD

**Issue by felipesfaria** [Xabaril/AspNetCore.Diagnostics.HealthChecks#586] opened 2020-07-16 14:40 UTC
**What happened**:
Using `AspNetCore.HealthChecks.SendGrid 3.1.1-preview1` and `SendGrid 9.18` health check fails with the following error:

```
fail: Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService[104]
      Health check sendgrid threw an unhandled exception after 40.3858ms
System.MissingMethodException: Method not found: 'Void SendGrid.SendGridClient..ctor(System.Net.Http.HttpClient, System.String, System.String, System.Collections.Generic.Dictionary`2<System.String,System.String>, System.String, System.String)'.
   at HealthChecks.SendGrid.SendGridHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at HealthChecks.SendGrid.SendGridHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.RunCheckAsync(IServiceScope scope, HealthCheckRegistration registration, CancellationToken cancellationToken)
```
 
**What you expected to happen**:
Health check to connect to sendgrid.

**How to reproduce it (as minimally and precisely as possible)**:
Run sample code and open /health.
Apikey doesn't matter in this sample since error happens before sending message to sendgrid.

**Source code sample**:
https://github.com/felipesfaria/HealthChecks.SendGrid.Sample

**Comment by manne** [comment] 2020-07-17 13:34
I can reproduce this issue with SendGrid version `9.18.0`.

Note: The [repo](https://github.com/felipesfaria/HealthChecks.SendGrid.Sample) uses version `9.14.1` (with this version it is working)

https://github.com/felipesfaria/HealthChecks.SendGrid.Sample/blob/0207d5e190f8def7e2348e6c4bb7fa18dc3c7944/HealthChecks.SendGrid.Sample/HealthChecks.SendGrid.Sample.csproj#L9

**Comment by unaizorrilla** [comment] 2020-07-22 16:10
Hi @manne , @felipesfaria 

is any braking change on 9.18.0 but version is minor :-(

I try to do some tests this week but if any of you discover the issue, please, let me know!

**Comment by dannyBies** [comment] 2020-07-23 21:14
It looks like this will be fixed once https://github.com/sendgrid/sendgrid-csharp/issues/1027 is resolved.

**Comment by dannyBies** [comment] 2020-09-13 12:12
I believe the sendgrid version in this library needs to be updated to at least version 9.20 to resolve this issue: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/a78815946a9678fc4b5e814b89dc53197a57d8e1/build/dependencies.props#L85

Unfortunately I don't have time in the forseeable future to open a PR and test it, just leaving this here for future reference.

**Closed** 2020-11-22 16:15 UTC
