### ISSUE TITLE
History timeline does not work on .NET Core 3, does on .NET Core 2.2

### ISSUE THREAD

**Issue by novotnycodestories** [Xabaril/AspNetCore.Diagnostics.HealthChecks#405] opened 2020-01-29 14:40 UTC
Hello, 
I am not able to get history timeline to work on .NET Core 3, using version of AspNetCore.HealthChecks.UI v3.0.9. Timeline works fine on netcoreapp2.2 with package 2.2.35. 
In netcoreapp3.0 project I simply register UI service using 
```
services.AddHealthChecksUI(setupSettings: settings => settings.AddHealthCheckEndpoint("Service", "http://127.0.0.1:50800/healthcheck"));
``` 
and then registers route using 
```
app.UseEndpoints(config =>
            {
                config.MapHealthChecks("/healthz");
                config.MapHealthChecksUI();
                config.MapControllers();
            });
```
In netcoreapp2.2 I do basically the same. No configuration from appsettings is used, no webhooks, no other nugets are installed in projects.
I also looked into DB file for both projects and in db file for netcoreapp3.0 the table HealthCheckExecutionHistories is empty but for netcoreapp2.2 it has some data, so it looks more like database-level issue than bug in UI.
Are there any special shenanigans that need to be done to make it work also on netcore 3?

**Comment by jonathan-bloodworth** [comment] 2020-03-03 09:46
@novotnycodestories Did you get anywhere with this? I tried your suggestion of downgrading to 2.2 but still didn't see any history and the histories table in the sqlite db was still empty.

**Comment by hptbee** [comment] 2020-03-05 10:43
![image](https://user-images.githubusercontent.com/18607352/75974118-dcfa7500-5f08-11ea-85fb-56bb40e03243.png)

**Comment by unaizorrilla** [comment] 2020-03-05 10:49
Hi @CarlosLanderas can you please following this issue?

**Comment by novotnycodestories** [comment] 2020-03-05 16:18
> @novotnycodestories Did you get anywhere with this? I tried your suggestion of downgrading to 2.2 but still didn't see any history and the histories table in the sqlite db was still empty.

No I havent progressed with this at all, however it was working on .net core 2.2, but you need to downgrade also nuget package (it worked for me though).

**Comment by CarlosLanderas** [comment] 2020-03-05 16:25
@novotnycodestories in your sample you are not using the UI Response Writer. Let me write a sample for you

**Comment by CarlosLanderas** [comment] 2020-03-05 16:33
Ok. I have reproduced the error. It looks like history entries are not being sent from the backend. Weird

**Comment by CarlosLanderas** [comment] 2020-03-05 16:49
@novotnycodestories @jonathan-bloodworth  @hptbee 

Could you try the sample HealthChecks.UIAndApi that is here?

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/master/samples/HealthChecks.UIAndApi

It is working for us.
I've also created a sample that is working with 3.0.9

Could you check that your database file is properly deleted and created on startup?

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HealthChecks.UI.Client;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Diagnostics.HealthChecks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using Microsoft.Extensions.Hosting;

namespace WebApplication
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddHealthChecksUI(setupSettings: setup =>
                    {
                        setup.AddHealthCheckEndpoint("endpoint1", "http://localhost:5000/healthz");
                    })
                .AddHealthChecks()
                .AddCheck("Random1", () =>
                    {
                        return DateTime.UtcNow.Millisecond % 2 == 0
                            ? HealthCheckResult.Healthy()
                            : HealthCheckResult.Unhealthy();
                    })
                .AddCheck("Random2", () =>
                {
                    return DateTime.UtcNow.Millisecond % 2 != 0
                        ? HealthCheckResult.Healthy()
                        : HealthCheckResult.Unhealthy();
                });
        }
        

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHealthChecks("/healthz", new HealthCheckOptions()
                {
                    Predicate = r => true,
                    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
                });

                endpoints.MapHealthChecksUI(setup => { setup.UIPath = "/ui"; });
            });
        }
    }
}
```

**Comment by hptbee** [comment] 2020-03-06 04:17
Hi @CarlosLanderas, I knew where the problem was this. The HealthCheckExecutionHistory  table just add record when current report status difference with execution status.
![1](https://user-images.githubusercontent.com/18607352/76050763-38754300-5f9b-11ea-9019-bc95cec1dc72.PNG)
 But In my case, i have many endpoints and  every endpoint i have many entries like this
![image](https://user-images.githubusercontent.com/18607352/76051002-fb5d8080-5f9b-11ea-9f43-1c869529e0f2.png)

**Comment by novotnycodestories** [comment] 2020-03-06 07:29
> @novotnycodestories in your sample you are not using the UI Response Writer. Let me write a sample for you

I am sorry for the misunderstanding, I didn't describe it entirely. 
I have server that uses healthcheck UI and collects healthchecks from other endpoints (using `AddHealthCheckEndpoint`). These endpoints have also sub checks for database, memory, etc, and all have correctly set response writer using `UIResponseWriter.WriteHealthCheckUIResponse`. 

Proposal for reproduction: 
Create two applications: 

- 1. with exposed healthcheck endpoint (/healthz) using response writer and with additional subchecks

- 2. with Healthcheck UI and targetting 1. application using `AddHealthCheckEndpoint`

**Comment by novotnycodestories** [comment] 2020-03-06 07:30
It can look like this 
![image](https://user-images.githubusercontent.com/17833494/76061861-bda12d80-5f84-11ea-8049-079938ddc9a6.png)

**Comment by CarlosLanderas** [comment] 2020-03-06 07:33
@novotnycodestories could you check the sample app I linked above? 

You can also test the code I pasted.

**Comment by novotnycodestories** [comment] 2020-03-06 08:27
> @novotnycodestories could you check the sample app I linked above?
> 
> You can also test the code I pasted.

Alright, I have tested both cases. 
First I tried the code you posted where application targets only itself and it works as expected.
![local_ui](https://user-images.githubusercontent.com/17833494/76064888-d14f9280-5f8a-11ea-8f56-5d1bd0c9c94b.JPG)
![local_db](https://user-images.githubusercontent.com/17833494/76064890-d1e82900-5f8a-11ea-9e2e-8aafec579e1f.JPG)

UI shows history timeline (somewhat) correctly and there are records in database.
Then I tried creating another application (other service) and targetted it by first application (local) as another endpoint. 
![image](https://user-images.githubusercontent.com/17833494/76065663-5a1afe00-5f8c-11ea-961b-f3418ad3bd9d.png)
And it actually did work on both .NET Core 3.0 and .NET Core 3.1. 
However I still cannot find difference between this and my production code. In production the table Failuers is straight empty and so timeline does not show anything... Dont know where to go with this.

**Comment by novotnycodestories** [comment] 2020-03-06 08:28
I wonder for how long some endpoint needs to stay in state to be saved into Failures table.

**Comment by novotnycodestories** [comment] 2020-03-06 09:36
Well, I found out that I had ridiculously high MinimumSecondsBetweenFailureNotifications and never waited for that long while I was testing it. I lowered it down and data are inserted properly into Failures table, however, the timeline is still empty ...
![r_db](https://user-images.githubusercontent.com/17833494/76071286-4d030c80-5f96-11ea-99a8-491112bb2648.JPG)

**Comment by unaizorrilla** [comment] 2020-03-06 09:41
Sorry but no sense! I hace the binaries on production año works well! Please check the elapsed time configured for collector and also check on browser the api response!!

**Comment by novotnycodestories** [comment] 2020-03-06 10:12
> Sorry but no sense! I hace the binaries on production año works well! Please check the elapsed time configured for collector and also check on browser the api response!!

Well, when it works for you it does not necessarily mean it works in all other use cases. I am also investing a lot of time into this to help you, me and potentially others, so please stop with It works on my machine syndrome. 

I may have an idea of why it does not work. State history is binded to Entry, right? What about a use case where I do not have any additional checks on my endpoint and I only care about the state of service itself (whether it is running or not). 
For this one particular service, the data from HC UI looks like this 
```
  {
    "id": 5,
    "status": "Healthy",
    "onStateFrom": "2020-03-06T10:36:53.668095+01:00",
    "lastExecuted": "2020-03-06T11:04:13.1703133+01:00",
    "uri": "http://rms.ysoft.local:50451/healthcheck",
    "name": "ReferenceProvider",
    "discoveryService": null,
    "entries": [],
    "history": []
  },
```
It has no entries (no DB checking, no custom HC checks, nothing, just plain `services.AddHealthChecks()` and thats all I need). 
I just want to track state of this service as whole.

**Comment by novotnycodestories** [comment] 2020-03-06 10:17
Well, bad thing about not having any additional entries is, that I cannot even show the history timeline if service responds as Healthy. 
![list](https://user-images.githubusercontent.com/17833494/76074634-f5679f80-5f9b-11ea-8e70-1052efdbe0d5.JPG)

**Comment by unaizorrilla** [comment] 2020-03-06 10:24
Well, this is a new scenario to check! Let me do some test on this, Meanwhile, can you add a simple entry (healthcheck) that always set Healthy status? This is how tipically do on k8s for  liveness .

Please let me know if the workaround fit for you!

**Comment by novotnycodestories** [comment] 2020-03-06 12:01
I have been able to make it work. I added empty check with **name** Endpoint (which is important, with any other name it didnt work). 
```
services.AddHealthChecks()
                .AddCheck("Endpoint", () => HealthCheckResult.Healthy())
```
The json result from api:
```
{
    "id": 6,
    "status": "Unhealthy",
    "onStateFrom": "2020-03-06T12:55:58.7437782+01:00",
    "lastExecuted": "2020-03-06T12:56:10.3483251+01:00",
    "uri": "http://10.0.5.211:50701/healthcheck",
    "name": "RemoteConfiguration",
    "discoveryService": null,
    "entries": [
      {
        "id": 8,
        "name": "Endpoint",
        "status": "Unhealthy",
        "description": "No connection could be made because the target machine actively refused it.",
        "duration": "00:00:00"
      }
    ],
    "history": [
      {
        "id": 1,
        "name": "Endpoint",
        "description": "No connection could be made because the target machine actively refused it.",
        "status": "Unhealthy",
        "on": "2020-03-06T12:54:51.5583478+01:00"
      },
      {
        "id": 2,
        "name": "Endpoint",
        "description": null,
        "status": "Healthy",
        "on": "2020-03-06T12:55:26.6596201+01:00"
      },
      {
        "id": 3,
        "name": "Endpoint",
        "description": "No connection could be made because the target machine actively refused it.",
        "status": "Unhealthy",
        "on": "2020-03-06T12:55:58.7437782+01:00"
      }
    ]
  }
```
And finally history timeline 
![image](https://user-images.githubusercontent.com/17833494/76081825-41214580-5faa-11ea-8276-b381abe377ec.png)

So this is the workaround I was looking for, thank you. 
I would suggest by default to add this empty check because your logic depends on it with a specific name and it may be, as proven by me, not very transparent.

**Comment by CarlosLanderas** [comment] 2020-03-09 10:00
Closing as resolved. Thanks everyone :)

**Closed by CarlosLanderas** 2020-03-09 10:00 UTC
Labels: bug
