### ISSUE TITLE
 Task Canceled Exception from SQL Server HealthCheck 

### ISSUE THREAD

**Issue by kushalshah5** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1826] opened 2023-05-30 05:17 UTC
**What happened**:
We are consistently encountering a TaskCanceledException from the SQL Server HealthCheck Readiness Endpoint during POD restarts.

**What you expected to happen**:
We expected the HealthCheck Endpoint to successfully execute the queries against the SQL Server and return a healthy status during POD restarts.

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy a distributed system with multiple PODs running

- Implement a HealthCheck Endpoint that periodically checks the connectivity with the SQL Server.

- Initiate a POD restart while the HealthCheck Endpoint is actively checking the server connection.

- Observe the occurrence of the "TaskCanceledException : A task was canceled." exception during the POD restart.

**Anything else we need to know?**:

We have noticed that the "Task Cancelled" exception occurs majorly during the POD restarts, indicating a potential connection disruption or unavailability of the SQL Server. This issue is not limited to the SQL Server HealthCheck endpoint; it also occurs for the Service Readiness HealthCheck, indicating a broader impact during POD restarts. 

**Environment**:

.NET Core version: [7.0](https://dotnet.microsoft.com/en-us/download/dotnet/7.0)
Healthchecks version: [6.0.2](https://www.nuget.org/packages/AspNetCore.HealthChecks.SqlServer/6.0.2)

**Comment by sungam3r** [comment] 2023-06-30 08:37
As I understand this behaviour is by design. `HealthCheckMiddleware` calls `healthCheckService.CheckHealthAsync` method passing `HttpContext.RequestAborted`. This token then is passed to `CreateLinkedTokenSource` for token for each healthcheck.
`HttpContext.RequestAborted` takes token from `HttpRequestLifetimeFeature.RequestAborted`. I did not go further, but I am sure that ultimately this chain reaches application lifetime token that receives termination signal on pod restart.

> We are consistently encountering a TaskCanceledException

Where exactly? Can you ignore it checking [app termination](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostapplicationlifetime?view=dotnet-plat-ext-7.0)?

**Comment by sungam3r** [comment] 2023-07-20 20:16
@kushalshah5 Closing for now. Feel free to reopen.

**Closed by sungam3r** 2023-07-20 20:17 UTC
